### ISSUE TITLE
視線移動をUV座標で移動する場合について

### ISSUE THREAD

**Issue by mizinco** [dwango/UniVRM#72]
ブレンドシェイププロキシで設定して、
プレイモードで試してみたのですが、上下移動しか反映されません。

インスペクター上では動いているのですが、
シーン上では上下のみです。時折びくっと左右に動く場合もあります。

https://twitter.com/CGmizinco/status/1069774857552879617
画像は上記に載せています。
コンソールのエラー表示は失念してました。

ご対応お願いいたします。

**Comment by yutopp** [comment]
Maybe fixed by https://github.com/dwango/UniVRM/wiki/ReleaseNote-v0.46%28ja%29#blendshapeproxy%E3%81%A7%E3%83%9E%E3%83%86%E3%83%AA%E3%82%A2%E3%83%AB%E3%81%AE%E3%82%AF%E3%83%AA%E3%82%A2%E6%8C%99%E5%8B%95%E3%82%92%E4%BF%AE%E6%AD%A3%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F. Please reopen this issue if there is still a bug which you reported. 🙏
